//
// SymptomType.swift
//

import Foundation

public enum SymptomType: String, Codable, CaseIterable, Localizable {
    case abdominalPain
    case acne
    case aggressive
    case anxiety
    case backPain
    case belching
    case blindness
    case bloating
    case bloodyStool
    case bloodyUrine
    case blurryVision
    case bruise
    case burningWhileUrinating
    case chestPain
    case chills
    case coldSweat
    case confusion
    case constipation
    case cough
    case dehydration
    case delirium
    case delusion
    case depression
    case diarrhoea
    case difficultyBreathing
    case difficultyConcentrating
    case difficultyFallingSleep
    case difficultyGettingAnErection
    case difficultySwallowing
    case dizzy
    case dryEyes
    case dryMouth
    case drySkin
    case earPain
    case excessiveThirst
    case exhausted
    case eyeIrritation
    case eyePain
    case eyeRedness
    case fatigue
    case fear
    case feelingCold
    case feelingHot
    case fever
    case flankPain
    case flatulence
    case footPain
    case forgetful
    case frequentUrination
    case guilt
    case hairLoss
    case hallucinations
    case handPain
    case headache
    case heartPalpitation
    case heartburn
    case heelPain
    case hives
    case hotFlash
    case hyperactivity
    case hyperventilation
    case increasedAlertness
    case increasedAppetite
    case increasedSexDrive
    case irritated
    case itchiness
    case itchyVagina
    case jointPain
    case jointStiffness
    case kneePain
    case lackOfMotivation
    case lethargy
    case lightSensitivity
    case lightheaded
    case lossOfAppetite
    case lowSexDrive
    case mania
    case memoryLoss
    case menstrualBleeding
    case moodSwings
    case moody
    case nasalCongestion
    case nausea
    case neckPain
    case nervous
    case nosebleed
    case numbness
    case painfulIntercourse
    case painfulSwallowing
    case painfulUrination
    case paleSkin
    case paranoia
    case psychosis
    case puffyEyes
    case rash
    case recurringNightmares
    case reflux
    case restless
    case restlessLegs
    case runnyNose
    case seizure
    case selfHarmThoughts
    case shivering
    case shortnessOfBreath
    case shoulderPain
    case sleepy
    case slurredSpeech
    case socialWithdrawal
    case soreThroat
    case stomachAche
    case stomachCramps
    case stress
    case suicidalThoughts
    case swollenFace
    case swollenFeet
    case swollenGums
    case swollenHands
    case swollenMouth
    case swollenNose
    case thinningHair
    case throwingUpBile
    case tingling
    case tinglingInFeet
    case tinglingInHands
    case tiredness
    case toothache
    case trembling
    case tremor
    case unconscious
    case unease
    case vaginalDischarge
    case vaginalIrritation
    case vaginalOdor
    case vomiting
    case weakness
    case weightGain
    case weightLoss
}
